## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.5
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
addons:
  apt_packages:
    - gfortran

cache:
 directories:
   - /home/travis/.julia/

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - julia --project --color=yes -e "import Pkg; Pkg.update(); Pkg.build()"
  - julia --project --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true);"
  - kill %1
  - echo "Test successful."

jobs:
  fast_finish: true
  allow_failures:
    - os: windows
    - os: osx
after_success: julia -e '
  using Pkg;
  Pkg.add("Coverage");
  using Coverage;
  Codecov.submit(process_folder());'
